export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_REQUEST_SUCCESS = 'FETCH_USERS_REQUEST_SUCCESS';
export const FETCH_USERS_REQUEST_FAILURE = 'FETCH_USERS_REQUEST_FAILURE';